# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LW3_v0n8FGnME3TK704yJyJrTnzzeTX7
"""



"""### **list**"""

!pip install numpy
#creating a list of 10 integer
numbers = [1,2,3,4,5,6,7,8,9,10]
print(numbers)
#sum,max,min
print('Sum',sum(numbers))
print('max',max(numbers))
print('Min',min(numbers))
#Add and remove element
numbers.append(50)
numbers.remove(4)
print('Updated List:',numbers)

#sort ascending and descending
print('Ascending:',sorted(numbers))
print('Descending:',sorted(numbers , reverse=True))

"""# `**tuples**`"""

#creating a tuple with 5 strings
fruits = ('apple','banana','orange','grapes','mango')
print(fruits)
#printing the secound last and last index
print('Secound Last:',fruits[-2])
print('Last:',fruits[-1])

#try to modify so give error or not
#fruits[1]='kiwi'

#now add element to touple through converting it is to list and then back to touple
fruits = list(fruits)
fruits.append('kiwi')
fruits = tuple(fruits)
print(fruits)

"""# **Dictionary**"""

#creating 5 keys-value of student and marks
student_marks = {
    'Alice': 85,
    'Bob': 92,
    'Charlie': 78,
    'David': 95,
    'Eve': 88
}
print(student_marks)
#print value and keys

"""# **Numpy**

# **Sets**
"""

#create sets
set1 = {1,2,3,4,5}
set2 = {4,5,6,7,8}
#union
print('Union:',set1.union(set2))
#intersection
print('Intersection:',set1.intersection(set2))
#difference
print('Difference:',set1.difference(set2))



"""# **Matplotib**"""